name: robot
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - bullet-cpp=3.09
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cycler=0.10.0
  - freetype=2.10.4
  - icu=58.2
  - intel-openmp=2020.2
  - jpeg=9b
  - kiwisolver=1.3.1
  - libpng=1.6.37
  - libtiff=4.1.0
  - lz4-c=1.9.3
  - matplotlib=3.4.1
  - matplotlib-base=3.4.1
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1k
  - pillow=8.2.0
  - pip=21.0.1
  - pybullet=3.09
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - python=3.8.5
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pywinusb=0.4.2
  - qt=5.9.7
  - setuptools=52.0.0
  - sip=4.19.13
  - six=1.15.0
  - sqlite=3.35.4
  - tk=8.6.10
  - tornado=6.1
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.36.2
  - wincertstore=0.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - cffi==1.14.5
    - easyhid==0.0.10
    - future==0.18.2
    - hid==1.0.4
    - iso8601==0.1.14
    - opencv-contrib-python==4.5.1.48
    - pycparser==2.20
    - pyyaml==5.4.1
