name: robot
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - bullet-cpp=3.09
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cycler=0.10.0
  - freetype=2.10.4
  - git=2.23.0
  - icu=68.1
  - jpeg=9d
  - kiwisolver=1.3.1
  - lcms2=2.12
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - liblapack=3.9.0
  - libpng=1.6.37
  - libtiff=4.2.0
  - lz4-c=1.9.3
  - matplotlib=3.4.1
  - matplotlib-base=3.4.1
  - mkl=2020.4
  - numpy=1.20.2
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - pip=21.0.1
  - pybullet=3.09
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyserial=3.4
  - python=3.8.5
  - python-dateutil
  - python_abi=3.8
  - qt=5.12.9
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.35.4
  - tk=8.6.10
  - tornado=6.1
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - cffi==1.14.5
    - easyhid==0.0.10
    - hidapi==0.10.1
    - future==0.18.2
    - iso8601==0.1.14
    - opencv-contrib-python==4.5.1.48
    - pillow==8.2.0
    - pycparser==2.20
    - pyyaml==5.4.1
    - serial==0.0.97
