name: robot
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - bullet-cpp=3.09
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cycler=0.10.0
  - dbus=1.13.18
  - expat=2.2.10
  - freetype=2.10.4
  - gettext=0.19.8.1
  - glib=2.66.1
  - icu=68.1
  - jpeg=9d
  - kiwisolver=1.3.1
  - krb5=1.17.1
  - lcms2=2.12
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcxx=11.1.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libpq=13.1
  - libtiff=4.2.0
  - libwebp-base=1.1.0
  - libxcb=1.13
  - llvm-openmp=11.1.0
  - lz4-c=1.9.3
  - matplotlib=3.4.1
  - matplotlib-base=3.4.1
  - mkl=2020.4
  - mysql-common=8.0.23
  - mysql-libs=8.0.23
  - ncurses=6.2
  - nspr=4.30
  - nss=3.64
  - numpy=1.20.2
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - pcre=8.44
  - pip=21.0.1
  - pthread-stubs=0.3
  - pybullet=3.17
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyserial=3.4
  - python=3.8.5
  - python-dateutil=2.8.1
  - python_abi=3.8
  - qt=5.12.9
  - readline=8.0
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.35.4
  - tk=8.6.10
  - tornado=6.1
  - wheel=0.36.2
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.7.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - cffi==1.14.5
    - easyhid==0.0.10
    - future==0.18.2
    - hidapi==0.10.1
    - iso8601==0.1.14
    - opencv-contrib-python==4.5.1.48
    - pillow==8.2.0
    - pycparser==2.20
    - pyyaml==5.4.1
    - serial==0.0.97
